# Generated by Django 5.0.14 on 2026-01-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='specialty',
        ),
    ]
